name: TileDB-Cloud-JDBC

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2019 ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true

      - run: |
          ./gradlew checkFormat
        shell: bash
        name: checkFormat

      - run: |
          ./gradlew assemble
        shell: bash
        name: assemble

      - name: test
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          ./gradlew test
        shell: bash

  Release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [Test]
    name: Create-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: false

      - name: Create-Jars
        run: unset SYSTEM; set +e; ./gradlew assemble; ./gradlew shadowJar; mkdir jars/; cp ./build/libs/*.jar jars/

      - name: Create-Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: jars/*.jar
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.tag_name }}
          draft: false
          prerelease: false
